### PR TITLE
WFDR-304-MiscFixes

### PR DESCRIPTION
**Pull request by setaDM**
## Summary of changes
Small changes or bug fixes.
## Trello Task link
https://trello.com/c/M8D7cdb1/80-304-misc-fixes
## Corresponding User Story Number and Title
N/A
## Detailed list of changes
- Smaller more compact footer was added to all pages and made static on the pages that needed it (Small pages)
- Limit of one week was put on the calendar for when the user creates an itinerary 
- Added error in case user manages to get the date pass one week (that way they cannot create the itinerary)
- Removed double title on view itinerary that devMain had
- Email formatting was changed
- Email delete bug was fixed
- Length cap was added to username, password, email, first and last name. (16,32,64,16,16 respectively)
- Added fix so email will only be sent when account is FULLY created. (Add preference page is completed)
- Properly centered admin table

### CODE REVIEW

**Comment by setaDM** [comment]
Fully tested myself w/ a new account. Made sure all settings work and are functional.

**Review by hilokiyz — APPROVED** [review]
Looks good to me!

**Review by plee99 — APPROVED** [review]
looks good fully tested

**Review by danielqyu — APPROVED** [review]
Looks good

**Review by NickMoo5 — APPROVED** [review]
Everything seems to be functioning :))

**Pull request merged**
