### PR TITLE
WDFR-207_Implementation_of_custom_error_pages_and_controller

### PR DESCRIPTION
**Pull request by hilokiyz**
## Summary of changes

Disabled default whitelabel error page and implements custom error pages

## Trello Task link

https://trello.com/c/bHyNQURC/60-207-update-whitelabel-error-page

## Corresponding User Story Number and Title

None

## Detailed list of changes

Updated application.properties: Added a new line to disable the default whitelabel error page

Added CustomErrorController.java: Implements custom error handing 

Added error folder in templates
Added error, error-404, error-500.html under error folder: Frontend templates to show new error with a button that redirects to login

### CODE REVIEW

**Review by danielqyu — APPROVED** [review]
looks good. new error page is displaying properly and redirecting to login

**Review by plee99 — APPROVED** [review]
seems to function as intended

**Review by setaDM — CHANGES_REQUESTED** [review]
Needs to have an error page for 405 errors. This error would be on our side, but I think It'd be nice to have in case it is needed.

**Review by setaDM — APPROVED** [review]
Should be good for now. We can always add more error pages in the future if needed.

**Pull request merged**
