### PR TITLE
WFDR-102-signup/profile_creation

### PR DESCRIPTION
**Pull request by hilokiyz**
Todo: Add username uniqueness validation from db, add in associated links to login

Done: Registration form, password validation (8 char+, uppercase, number, specialchar), password verification, register button locking when password conditions aren't met (also include username uniqueness as a condition too)

### CODE REVIEW

**Comment by hilokiyz** [comment]
Form output variables:
fname = first name
lname = last name
email = email address
username = used to login (check for any duplicates?)
password-input = used for login
password2 = repeated password

**Review by NickMoo5 — APPROVED** [review]
Looks good

**Review by danielqyu — APPROVED** [review]
looks good to me

**Review by setaDM — APPROVED** [review]
Looks good to me.

**Pull request merged**
