### PR TITLE
WFDR-321-ViewUserTrips

### PR DESCRIPTION
**Pull request by plee99**
## Summary of changes
- added page for viewing previous trips
- added nav bar with links to viewTrips page --> added to all needed pages
- modified tripDisplay GetMapping to handle specific trip ID's
- 
## Trello Task link
https://trello.com/c/sjfd3aib/79-321-view-user-trips

## Corresponding User Story Number and Title
User case #11: View Previous Trips

## Detailed list of changes
implemented exception case for when the user has not generated any itineraries

### CODE REVIEW

**Review by NickMoo5 — CHANGES_REQUESTED** [review]
image
Can we have the profile vertically centered to match the rest of the nav bar. It looks off right now.

image
Center the line of date/budget so it's consistent with the title

image
Can you style this more or make it bigger or smth. The plain text looks out of place. Could change the text to smth like "You don't have any trips yet, time to start making some adventures" or idk you made lots of nice bits of text for the fluff page take some inspiration from that.

Functionally it looks to be all working. :))

**Comment by plee99** [comment]
All requested changes done. Also added in google api for the image in trip display and put the location, dates, and budget inside the picture so it more aligns with our other pages. I can remove this if others think its unecessary, take a look: 
image

image

image

image

**Review by setaDM — CHANGES_REQUESTED** [review]
Not sure how the trips are currently ordered, but they aren't ordered by the UID. It should be sorted in ascending order that way the newer trips are at the bottom.

**Review by setaDM — APPROVED** [review]
Looks like it's good to go now. The new features work and the old features seem like they didnt break. 👍

**Review by NickMoo5 — APPROVED** [review]
Everything looks good now and is functioning

**Pull request merged**
