### PR TITLE
WFDR-111 Link Data Base

### PR DESCRIPTION
**Pull request by NickMoo5**
This request is to merge the database and user models into devMain
Changes:
- setup postgres db on render
- create user class with the following attributes: first and last name, user and password, account type (admin, user), email, uid
- create userRepository with a findByUserAndPass method for login verification and findByUser(finds if username exists) for account creation

### CODE REVIEW

**Review by danielqyu — APPROVED** [review]
looks good to me :)

**Review by hilokiyz — APPROVED** [review]
Looks good

**Comment by setaDM** [comment]
Code looks good.

**Review by setaDM — APPROVED** [review]
Code looks good.

**Pull request merged**
