### PR TITLE
Wfdr-206-TripDisplayPage_frontend

### PR DESCRIPTION
**Pull request by plee99**
## Summary of changes
- integrated bootstrap template for design elements in user landing and trip display pages
- merged files from template to project folders
- integrated thymeleaf to both pages
- added forms for trip display page (might need modification as user.username, etc... does not show only in tripDisplay.html page)

## Trello Task link
https://trello.com/c/518KeVSA/35-206-tripdisplaypagefrontend

## Corresponding User Story Number and Title
Use Case #5 - Adding new itinerary

## Detailed list of changes
Folder structure:

src -->
---- resources -->
-------------- static -->
--------------------- css --> (css files for individual pages/overall styling)
--------------------- images --> (images used for front end)
--------------------- js --> (scripts for individual pages)
--------------------- vendor --> (themes, fonts, components)

-------------- templates -->
---------------------- admin --> (admin specific html pages)
---------------------- user --> (user specific html pages, ex. tripDisplay.html login.html)

### CODE REVIEW

**Review by NickMoo5 — CHANGES_REQUESTED** [review]
-Can we change the placeholder text for selecting a city to "Enter a city" since it's meant to be text entered by the user

**Review by NickMoo5 — CHANGES_REQUESTED** [review]
On the Trip Display page, clicking the WayFinder logo in top left leads to an error. The logo needs to be mapped back to landing.

Same as the userlanding page, if I click the WayFinder logo, I get whitelabel error. Logo needs to be mapped.

**Comment by plee99** [comment]
- Modified "Select City" to "Enter a City"
- fixed mapping for preference settings on tripDisplay page
- removed mapping on user landing, not necessary
- updated forms for new trip display page.

image

**Review by NickMoo5 — CHANGES_REQUESTED** [review]
remove country from ttrip display page

**Pull request merged**
