### PR TITLE
WFDR-320-GoogleMapsAPI

### PR DESCRIPTION
**Pull request by hilokiyz**
## Summary of changes

Added Google Maps API
Implemented maps to trip display
Added background image retriever to trip display
Added nearby restaurants search and markers to display results
Added infowindow to markers

## Trello Task link

https://trello.com/c/XimCSps9/64-320-google-api-setup
https://trello.com/c/qgRwatoW/68-3201-routes-api-setup-and-basic-display
https://trello.com/c/ToMxGwag/75-3203-consolidate-to-trip-display

## Corresponding User Story Number and Title

User case 5: Creating new itinerary

## Detailed list of changes

TripDisplay:
- Added script to implement google maps API
- Added div to each collapsible div to add map
- Added script to display a relevant background image from google maps based on origin city
- Added script to display a new map for each collapsible div
- Added function and handling to get location coordinates and center the respective map to the location
- Added function to search nearby restaurants based restricted to max price 
- Added function to restrict getdetails results to max 5 entries per restaurant search
- Added function to display marker based on results
- Added function to display detailed results to each marker

### CODE REVIEW

**Review by NickMoo5 — COMMENTED** [review]
The Maps look amazing and great that you figured out how to completely remove the whitespace if a map location wasn't found for a place. 

I'm not sure where but we should probably have some small blurb of text on that page hinting or implying that "recommended" restaurants are indicated on the map. Can also see what everyone else thinks on how this message should be conveyed.

Is it possible to have a location indicator that isn't red to indicate the exact location of the attraction? If it's too arduous then don't bother. Just a thought I had.

All of it though is really amazing good work in getting this nightmare to function!

**Review by danielqyu — APPROVED** [review]
really great job. everything is working for me

I agree with nick that it's not really implied that the maps are specifically showing.

maybe something like this?
image

**Comment by hilokiyz** [comment]
Potentially adding a notice at the top about nearby restaurants being red would help

Additionally added markers for each location 

image

**Comment by hilokiyz** [comment]
image

Added footnote to maps notifying user of restaurant markers

**Review by plee99 — APPROVED** [review]
Awesome work hilo, everything working for me also, only minor change would be to make the map a tiny bit smaller for each event but its not that necessary so im gonna go ahead and approve

**Review by setaDM — APPROVED** [review]
If possible - when the map doesn't get displayed because google maps cant find it or for whatever reason. Could you make it so it doesn't display the 'restaurants are displayed as red markers' text underneath the map? Instead just have nothing or something along the lines of google maps could not find the map of the location. 

If you're unable to then it's fine. You did a good job on the maps. :)

**Pull request closed without merging**
