### PR TITLE
WFDR-203-Signup_Validation

### PR DESCRIPTION
**Pull request by plee99**
## Summary of changes
on registration page, users have to now click on the password and repeat password inputs to trigger validation

## Trello Task link
https://trello.com/c/17kQifWa/51-203-change-signup-validation-feedback-to-be-displayed-in-real-time-add-any-missing-validation

## Corresponding User Story Number and Title
User Story #1 - Making a New Account

### CODE REVIEW

**Comment by hilokiyz** [comment]
Two errors when testing:

1. If the first character of the password matches one of the three requirements (number, capital letter, symbol), and you delete the character, the invalid version of the requirement will not show up

image

2. When both passwords are one character and the same. and you delete the initial password, the repeat password will still show that both passwords match

image

**Comment by plee99** [comment]
should be fixed now

image

image

**Review by setaDM — APPROVED** [review]
Seems to properly update validation of the entered password in real time.

**Review by danielqyu — APPROVED** [review]
looks to be functioning as intented to me

**Review by hilokiyz — APPROVED** [review]
Looks good to me now when I tested it out

**Pull request merged**
