### PR TITLE
WFDR-301-HomePage

### PR DESCRIPTION
**Pull request by plee99**
## Summary of changes
Created from David's WFDR-310-AdminEdit/RemoveUsers branch because I needed to see all UI updates
- created home (fluff) page with links to login and registration
- remapped (''/') to home page
- updated user account icon on all pages
-
## Trello Task link
https://trello.com/c/YPNvU49J/71-301-home-page-fluff-page

## Corresponding User Story Number and Title
none

## Detailed list of changes
- home.html creation
- changed profile icon for all pages
- added home page link to footer for all pages

- modified User Controller to accommodate new home.html fluff page
    - home page should be first page user sees when starting web app

### CODE REVIEW

**Review by NickMoo5 — CHANGES_REQUESTED** [review]
image
Can you add some padding between the pic and footer.

"and accommodation options" - Let's also take this out of the fluff message on the home page.

When the user signs out they should be brought to the home page, currently it redirects user to login page.

Upon loading into the webpage, it seem to need a bit of time to load the video and some elements:
image
If you move these 2 from the end of the body to inside the header this problem is solved as it'll be rendered and loaded before the rest of the webpage.

Rest looks good; pretty fluff page

**Review by danielqyu — APPROVED** [review]
looks good to me, ill add the about us page to be linked in the footer

**Review by hilokiyz — CHANGES_REQUESTED** [review]
I would recommend moving the "Signup Here" button to maybe under the "start your adventure" button, and potentially changing the color of the latter button so it's more visible

**Comment by plee99** [comment]
all requested changes completed

**Review by setaDM — APPROVED** [review]
Home fluff page looks really nice. I like the new logo too. Maybe on the home page - the footer shouldn't have the home redirect available there, however that is quite minor so I'm still going to approve it. It can maybe just be quickly changed before merging.  Looks like all the pages had the footer / logo changed and nothing broke so should be good to go.

**Comment by plee99** [comment]
removed link to home page on home.html, should be ready to merge

**Review by NickMoo5 — APPROVED** [review]
Looks good, the Google api integrated textbox functions correctly still. Good to merge

**Pull request merged**
