### PR TITLE
WFDR-213-ProcessChatQueryResponse

### PR DESCRIPTION
**Pull request by NickMoo5**
## Summary of changes
Integrate ChatGpt into the workflow of the user to generate a trip
Implented Trip DB 
Fixed UI errors and erroneous code
## Trello Task link
https://trello.com/c/FwO4H2aG/61-213-generate-trip-query-and-parsing-response

## Corresponding User Story Number and Title
User Story #5 (Partial)
Add new Itinerary

## Detailed list of changes

- Integrated ChatGpt query of a list of locations/activities given a location and some parameters. (To be expanded upon and customized in Iteration3
- Implement asynchronous execution of the chatGpt query to run in background as it takes time
- Added spinner and change in UI to indicate to user to wait.
- Added error handling for chatGpt querying and accompanying error msgs displayed to user if it occurs
- Added Trip db to store trips, Added subsequent helpers and repo setup
- General UI fixes and logic fixes

### CODE REVIEW

**Review by hilokiyz — APPROVED** [review]
No existing errors have been seen from testing, looks good to me

**Review by plee99 — APPROVED** [review]
no errors found, ready to merge

**Review by setaDM — APPROVED** [review]
Tested all settings, endpoints and features and they seem to be working as intended.

**Review by danielqyu — APPROVED** [review]
looks good. ran it through and tested most things I could find

**Pull request merged**
